#!/bin/bash
#BSUB -q hp12
#BSUB -x
# bsub -o out
# bsub -e err
#BSUB -J anyname

# ~~~!!!YOU MUST HAVE PROTEIN.pdbqt AND LIGAND.pdbqt FILES IN YOUR HOME DIRECTORY ON THE CLUSTER FOR THIS TO WORK!!!~~~ 
#			(but you don't need anything else, besides this script appropriately modified for your docking)

/share/apps/autodock/autodock_vina_1_1_2_linux_x86/bin/vina \             # don't mess with this line
--receptor /home/zsiegel/PROTEIN.pdbqt \                                  # modify me (see below)
--ligand /home/zsiegel/LIGAND.pdbqt \                                     # modify me
--center_x 0 \                                                            # modify me 
--center_y 0 \                                                            # modify me 
--center_z 0 \                                                            # modify me 
--size_x 0 \                                                              # modify me 
--size_y 0 \                                                              # modify me 
--size_z 0 \                                                              # modify me 
--out /home/zsiegel/RESULT.pdbqt \                                        # modify me 
--log /home/zsiegel/LOG.txt \                                             # modify me 
--exhaustiveness 0 \                                                      # modify me 



# everything below this line is just notes and has nothing to do with the actual script (you don't need to include it in the end script)


# MODIFY THE STUFF ABOVE AS FOLLOWS:
#
# Replace PROTEIN, LIGAND, RESULT, LOG with appropriate names
#	PROTEIN is the .pdbqt file you made in AutoDock. 
#		Be sure your file name has no spaces or weird characters in it and that the name is exactly the same as the one in your cluster home directory.
#	Likewise for LIGAND
#	RESULT is the pdbqt with the actual binding configurations, LOG is a list of binding energies; these are files Vina makes, so name them whatever you want.
# Replace zsiegel with your username
# Replace all the 0's with appropriate numbers
#	Center_x/y/z and size_x/y/z are the parameters for your grid box. 
#		You need look at your protein in AutoDock to figure out what this is, then replace each 0 with the appropriate number from the grid box editing window.
#		There is no need to save a .gpf file, but I recommend writing down your grid box parameters and/or taking a screen shot.
# 	Exhaustiveness is how thoroughly the dock goes. 
# 		8 is the minimum. (I believe this number must be an integer.)
# 		This number correlates with how long it takes to dock (although it also takes longer with a larger grid box).
# 			E.g. a docking I did with exhaustiveness 50 took 13433.80 sec (~4 hours), but another with a smaller grid box and exhaustiveness 8 took 372.44 sec.
#
# ***DON'T MESS WITH THE " /" at the end of each line, it just lets me split this into a bunch of lines instead of one big long one.

 
# Make sure you save this file in your home directory *with no file extension*
# To submit it, log onto the cluster in terminal and enter "bsub < SCRIPTNAME" where SCRIPTNAME is whatever file name you give this script after modiying it.
#
# In the end you will get a RESULT.pdbqt file that you can open in PyMol or Chimera
# You will also get a log file that looks like this
 

# More info at http://vina.scripps.edu/manual.html

# by Zarek Siegel 4/9/15